import { NextRequest, NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function POST(req: NextRequest) {
  try { await requireAdmin() } catch { return NextResponse.json({ error: 'Forbidden' }, { status: 403 }) }
  const { name, location } = await req.json()
  if (!name) return NextResponse.json({ error: 'Missing name' }, { status: 400 })
  // apiKey auto-generated by Prisma default (cuid)
  const machine = await prisma.machine.create({ data: { name, location: location || '', espIp: '' } })
  return NextResponse.json(machine) // returns machine (includes apiKey)
}

export async function DELETE(req: NextRequest) {
  try { await requireAdmin() } catch { return NextResponse.json({ error: 'Forbidden' }, { status: 403 }) }
  const { id } = await req.json()
  await prisma.machine.delete({ where: { id } })
  return NextResponse.json({ ok: true })
}
